//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLConnect.TraceLink {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:tracelink:soap", ConfigurationName="TraceLink.snrequest")]
    public interface snrequest {
        
        // CODEGEN: Parameter "SNResponse" erfordert zusätzliche Schemainformationen, die nicht mit dem Parametermodus erfasst werden können. Das spezifische Attribut ist "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="urn:tracelink:soap:snrequest:serialNumbersRequestRequest", ReplyAction="urn:tracelink:soap:snrequest:serialNumbersRequestResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="SNResponse")]
        TLConnect.TraceLink.serialNumbersRequestResponse serialNumbersRequest(TLConnect.TraceLink.serialNumbersRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:tracelink:soap:snrequest:serialNumbersRequestRequest", ReplyAction="urn:tracelink:soap:snrequest:serialNumbersRequestResponse")]
        System.Threading.Tasks.Task<TLConnect.TraceLink.serialNumbersRequestResponse> serialNumbersRequestAsync(TLConnect.TraceLink.serialNumbersRequestRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1658.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:tracelink:soap")]
    public enum idType {
        
        /// <remarks/>
        GS1_SER,
        
        /// <remarks/>
        CN_SER,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1658.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:tracelink:soap")]
    public enum encodingType {
        
        /// <remarks/>
        SGTIN,
        
        /// <remarks/>
        SSCC,
        
        /// <remarks/>
        CN_EDMC,
        
        /// <remarks/>
        NTIN,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1658.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:tracelink:soap")]
    public partial class objectKey : object, System.ComponentModel.INotifyPropertyChanged {
        
        private objectIdentifierType nameField;
        
        private bool nameFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public objectIdentifierType Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NameSpecified {
            get {
                return this.nameFieldSpecified;
            }
            set {
                this.nameFieldSpecified = value;
                this.RaisePropertyChanged("NameSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1658.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:tracelink:soap")]
    public enum objectIdentifierType {
        
        /// <remarks/>
        GTIN,
        
        /// <remarks/>
        NTIN,
        
        /// <remarks/>
        COMPANY_PREFIX,
        
        /// <remarks/>
        CN_RESCODE,
        
        /// <remarks/>
        CN_SUBTYPE_LEVEL_RATIO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1658.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:tracelink:soap")]
    public partial class errorMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("ErrorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1658.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:tracelink:soap")]
    public partial class interval : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numberFromField;
        
        private string numberToField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string NumberFrom {
            get {
                return this.numberFromField;
            }
            set {
                this.numberFromField = value;
                this.RaisePropertyChanged("NumberFrom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string NumberTo {
            get {
                return this.numberToField;
            }
            set {
                this.numberToField = value;
                this.RaisePropertyChanged("NumberTo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1658.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:tracelink:soap")]
    public partial class SNResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string receivingSystemField;
        
        private string sendingSystemField;
        
        private string actionCodeField;
        
        private encodingType encodingTypeField;
        
        private bool encodingTypeFieldSpecified;
        
        private idType iDTypeField;
        
        private bool iDTypeFieldSpecified;
        
        private interval intervalField;
        
        private objectKey objectKeyField;
        
        private ReferenceDocuments referenceDocumentsField;
        
        private string[] randomizedNumberListField;
        
        private errorMessage rfidExceptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ReceivingSystem {
            get {
                return this.receivingSystemField;
            }
            set {
                this.receivingSystemField = value;
                this.RaisePropertyChanged("ReceivingSystem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string SendingSystem {
            get {
                return this.sendingSystemField;
            }
            set {
                this.sendingSystemField = value;
                this.RaisePropertyChanged("SendingSystem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ActionCode {
            get {
                return this.actionCodeField;
            }
            set {
                this.actionCodeField = value;
                this.RaisePropertyChanged("ActionCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public encodingType EncodingType {
            get {
                return this.encodingTypeField;
            }
            set {
                this.encodingTypeField = value;
                this.RaisePropertyChanged("EncodingType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EncodingTypeSpecified {
            get {
                return this.encodingTypeFieldSpecified;
            }
            set {
                this.encodingTypeFieldSpecified = value;
                this.RaisePropertyChanged("EncodingTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public idType IDType {
            get {
                return this.iDTypeField;
            }
            set {
                this.iDTypeField = value;
                this.RaisePropertyChanged("IDType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IDTypeSpecified {
            get {
                return this.iDTypeFieldSpecified;
            }
            set {
                this.iDTypeFieldSpecified = value;
                this.RaisePropertyChanged("IDTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public interval Interval {
            get {
                return this.intervalField;
            }
            set {
                this.intervalField = value;
                this.RaisePropertyChanged("Interval");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public objectKey ObjectKey {
            get {
                return this.objectKeyField;
            }
            set {
                this.objectKeyField = value;
                this.RaisePropertyChanged("ObjectKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public ReferenceDocuments ReferenceDocuments {
            get {
                return this.referenceDocumentsField;
            }
            set {
                this.referenceDocumentsField = value;
                this.RaisePropertyChanged("ReferenceDocuments");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        [System.Xml.Serialization.XmlArrayItemAttribute("SerialNo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] RandomizedNumberList {
            get {
                return this.randomizedNumberListField;
            }
            set {
                this.randomizedNumberListField = value;
                this.RaisePropertyChanged("RandomizedNumberList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public errorMessage RfidException {
            get {
                return this.rfidExceptionField;
            }
            set {
                this.rfidExceptionField = value;
                this.RaisePropertyChanged("RfidException");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1658.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tracelink.com/snx")]
    public partial class ReferenceDocuments : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string pONumberField;
        
        private string pOLineField;
        
        private string workOrderNumberField;
        
        private string referenceIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string PONumber {
            get {
                return this.pONumberField;
            }
            set {
                this.pONumberField = value;
                this.RaisePropertyChanged("PONumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string POLine {
            get {
                return this.pOLineField;
            }
            set {
                this.pOLineField = value;
                this.RaisePropertyChanged("POLine");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string WorkOrderNumber {
            get {
                return this.workOrderNumberField;
            }
            set {
                this.workOrderNumberField = value;
                this.RaisePropertyChanged("WorkOrderNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string ReferenceId {
            get {
                return this.referenceIdField;
            }
            set {
                this.referenceIdField = value;
                this.RaisePropertyChanged("ReferenceId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="serialNumbersRequest", WrapperNamespace="urn:tracelink:soap", IsWrapped=true)]
    public partial class serialNumbersRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:tracelink:soap", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SendingSystem;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:tracelink:soap", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReceivingSystem;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:tracelink:soap", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TLConnect.TraceLink.idType IdType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:tracelink:soap", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TLConnect.TraceLink.encodingType EncodingType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:tracelink:soap", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Size;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:tracelink:soap", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TLConnect.TraceLink.objectKey ObjectKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:tracelink:soap", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RequestRandomizedNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:tracelink:soap", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TLConnect.TraceLink.ReferenceDocuments ReferenceDocuments;
        
        public serialNumbersRequestRequest() {
        }
        
        public serialNumbersRequestRequest(string SendingSystem, string ReceivingSystem, TLConnect.TraceLink.idType IdType, TLConnect.TraceLink.encodingType EncodingType, int Size, TLConnect.TraceLink.objectKey ObjectKey, string RequestRandomizedNumber, TLConnect.TraceLink.ReferenceDocuments ReferenceDocuments) {
            this.SendingSystem = SendingSystem;
            this.ReceivingSystem = ReceivingSystem;
            this.IdType = IdType;
            this.EncodingType = EncodingType;
            this.Size = Size;
            this.ObjectKey = ObjectKey;
            this.RequestRandomizedNumber = RequestRandomizedNumber;
            this.ReferenceDocuments = ReferenceDocuments;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="serialNumbersRequestResponse", WrapperNamespace="urn:tracelink:soap", IsWrapped=true)]
    public partial class serialNumbersRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:tracelink:soap", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TLConnect.TraceLink.SNResponse SNResponse;
        
        public serialNumbersRequestResponse() {
        }
        
        public serialNumbersRequestResponse(TLConnect.TraceLink.SNResponse SNResponse) {
            this.SNResponse = SNResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface snrequestChannel : TLConnect.TraceLink.snrequest, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class snrequestClient : System.ServiceModel.ClientBase<TLConnect.TraceLink.snrequest>, TLConnect.TraceLink.snrequest {
        
        public snrequestClient() {
        }
        
        public snrequestClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public snrequestClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public snrequestClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public snrequestClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TLConnect.TraceLink.serialNumbersRequestResponse TLConnect.TraceLink.snrequest.serialNumbersRequest(TLConnect.TraceLink.serialNumbersRequestRequest request) {
            return base.Channel.serialNumbersRequest(request);
        }
        
        public TLConnect.TraceLink.SNResponse serialNumbersRequest(string SendingSystem, string ReceivingSystem, TLConnect.TraceLink.idType IdType, TLConnect.TraceLink.encodingType EncodingType, int Size, TLConnect.TraceLink.objectKey ObjectKey, string RequestRandomizedNumber, TLConnect.TraceLink.ReferenceDocuments ReferenceDocuments) {
            TLConnect.TraceLink.serialNumbersRequestRequest inValue = new TLConnect.TraceLink.serialNumbersRequestRequest();
            inValue.SendingSystem = SendingSystem;
            inValue.ReceivingSystem = ReceivingSystem;
            inValue.IdType = IdType;
            inValue.EncodingType = EncodingType;
            inValue.Size = Size;
            inValue.ObjectKey = ObjectKey;
            inValue.RequestRandomizedNumber = RequestRandomizedNumber;
            inValue.ReferenceDocuments = ReferenceDocuments;
            TLConnect.TraceLink.serialNumbersRequestResponse retVal = ((TLConnect.TraceLink.snrequest)(this)).serialNumbersRequest(inValue);
            return retVal.SNResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TLConnect.TraceLink.serialNumbersRequestResponse> TLConnect.TraceLink.snrequest.serialNumbersRequestAsync(TLConnect.TraceLink.serialNumbersRequestRequest request) {
            return base.Channel.serialNumbersRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<TLConnect.TraceLink.serialNumbersRequestResponse> serialNumbersRequestAsync(string SendingSystem, string ReceivingSystem, TLConnect.TraceLink.idType IdType, TLConnect.TraceLink.encodingType EncodingType, int Size, TLConnect.TraceLink.objectKey ObjectKey, string RequestRandomizedNumber, TLConnect.TraceLink.ReferenceDocuments ReferenceDocuments) {
            TLConnect.TraceLink.serialNumbersRequestRequest inValue = new TLConnect.TraceLink.serialNumbersRequestRequest();
            inValue.SendingSystem = SendingSystem;
            inValue.ReceivingSystem = ReceivingSystem;
            inValue.IdType = IdType;
            inValue.EncodingType = EncodingType;
            inValue.Size = Size;
            inValue.ObjectKey = ObjectKey;
            inValue.RequestRandomizedNumber = RequestRandomizedNumber;
            inValue.ReferenceDocuments = ReferenceDocuments;
            return ((TLConnect.TraceLink.snrequest)(this)).serialNumbersRequestAsync(inValue);
        }
    }
}
